# Generated by Django 5.1.6 on 2025-02-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='bootstrap_theme',
            field=models.CharField(blank=True, help_text='URL to a custom Bootstrap theme', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='custom_css',
            field=models.FileField(blank=True, null=True, upload_to='static/css/schools/'),
        ),
        migrations.AddField(
            model_name='school',
            name='custom_html',
            field=models.FileField(blank=True, null=True, upload_to='templates/schools/'),
        ),
        migrations.AddField(
            model_name='school',
            name='custom_js',
            field=models.FileField(blank=True, null=True, upload_to='static/js/schools/'),
        ),
    ]
